Procedure LoadSounds;
Begin
  OpenSoundResourceFile('ZVUKY\zvuky.snd');
  LoadSound(ZvukRaw[0],'BLASTER1');
  LoadSound(ZvukRaw[1],'BLASTER2');
  LoadSound(ZvukRaw[2],'BLASTER3');
  LoadSound(ZvukRaw[3],'MANTRA');
  LoadSound(ZvukRaw[4],'ASMR');
  LoadSound(ZvukRaw[5],'WAKE-UP');
  LoadSound(ZvukRaw[6],'MUSIC432');
  LoadSound(ZvukRaw[7],'WAKEUP1');
  LoadSound(ZvukRaw[8],'WAKEUP2');

  LoadSound(ZvukRaw[9], '01-01');
  LoadSound(ZvukRaw[10],'01-02');
  LoadSound(ZvukRaw[11],'01-03');
  LoadSound(ZvukRaw[12],'01-04');
  LoadSound(ZvukRaw[13],'01-05');
  LoadSound(ZvukRaw[14],'01-06');
  LoadSound(ZvukRaw[15],'01-07');
  LoadSound(ZvukRaw[16],'01-08');

  LoadSound(ZvukRaw[17],'02-01');
  LoadSound(ZvukRaw[18],'02-02');
  LoadSound(ZvukRaw[19],'02-03');
  LoadSound(ZvukRaw[20],'02-04');
  LoadSound(ZvukRaw[21],'02-05');
  LoadSound(ZvukRaw[22],'02-06');
  LoadSound(ZvukRaw[23],'02-07');
  LoadSound(ZvukRaw[24],'02-08');

  LoadSound(ZvukRaw[25],'03-01');
  LoadSound(ZvukRaw[26],'03-02');
  LoadSound(ZvukRaw[27],'03-03');
  LoadSound(ZvukRaw[28],'03-04');
  LoadSound(ZvukRaw[29],'03-05');
  LoadSound(ZvukRaw[30],'03-06');
  LoadSound(ZvukRaw[31],'03-07');
  LoadSound(ZvukRaw[32],'03-08');

  LoadSound(ZvukRaw[33],'04-01');
  LoadSound(ZvukRaw[34],'04-02');
  LoadSound(ZvukRaw[35],'04-03');
  LoadSound(ZvukRaw[36],'04-04');
  LoadSound(ZvukRaw[37],'04-05');
  LoadSound(ZvukRaw[38],'04-06');
  LoadSound(ZvukRaw[39],'04-07');
  LoadSound(ZvukRaw[40],'04-08');

  LoadSound(ZvukRaw[41],'05-01');
  LoadSound(ZvukRaw[42],'05-02');
  LoadSound(ZvukRaw[43],'05-03');
  LoadSound(ZvukRaw[44],'05-04');
  LoadSound(ZvukRaw[45],'05-05');
  LoadSound(ZvukRaw[46],'05-06');
  LoadSound(ZvukRaw[47],'05-07');
  LoadSound(ZvukRaw[48],'05-08');

  LoadSound(ZvukRaw[49],'06-01');
  LoadSound(ZvukRaw[50],'06-02');
  LoadSound(ZvukRaw[51],'06-03');
  LoadSound(ZvukRaw[52],'06-04');
  LoadSound(ZvukRaw[53],'06-05');
  LoadSound(ZvukRaw[54],'06-06');
  LoadSound(ZvukRaw[55],'06-07');
  LoadSound(ZvukRaw[56],'06-08');

  LoadSound(ZvukRaw[57],'07-01');
  LoadSound(ZvukRaw[58],'07-02');
  LoadSound(ZvukRaw[59],'07-03');
  LoadSound(ZvukRaw[60],'07-04');
  LoadSound(ZvukRaw[61],'07-05');
  LoadSound(ZvukRaw[62],'07-06');
  LoadSound(ZvukRaw[63],'07-07');
  LoadSound(ZvukRaw[64],'07-08');

  LoadSound(ZvukRaw[65],'08-01');
  LoadSound(ZvukRaw[66],'08-02');
  LoadSound(ZvukRaw[67],'08-03');
  LoadSound(ZvukRaw[68],'08-04');
  LoadSound(ZvukRaw[69],'08-05');
  LoadSound(ZvukRaw[70],'08-06');
  LoadSound(ZvukRaw[71],'08-07');
  LoadSound(ZvukRaw[72],'08-08');

  LoadSound(ZvukRaw[73],'09-01');
  LoadSound(ZvukRaw[74],'09-02');
  LoadSound(ZvukRaw[75],'09-03');
  LoadSound(ZvukRaw[76],'09-04');
  LoadSound(ZvukRaw[77],'09-05');
  LoadSound(ZvukRaw[78],'09-06');
  LoadSound(ZvukRaw[79],'09-07');
  LoadSound(ZvukRaw[80],'09-08');

  LoadSound(ZvukRaw[81],'10-01');
  LoadSound(ZvukRaw[82],'10-02');
  LoadSound(ZvukRaw[83],'10-03');
  LoadSound(ZvukRaw[84],'10-04');
  LoadSound(ZvukRaw[85],'10-05');
  LoadSound(ZvukRaw[86],'10-06');
  LoadSound(ZvukRaw[87],'10-07');
  LoadSound(ZvukRaw[88],'10-08');

  LoadSound(ZvukRaw[89],'11-01');
  LoadSound(ZvukRaw[90],'11-02');
  LoadSound(ZvukRaw[91],'11-03');
  LoadSound(ZvukRaw[92],'11-04');
  LoadSound(ZvukRaw[93],'11-05');
  LoadSound(ZvukRaw[94],'11-06');
  LoadSound(ZvukRaw[95],'11-07');
  LoadSound(ZvukRaw[96],'11-08');

  LoadSound(ZvukRaw[97],'12-01');
  LoadSound(ZvukRaw[98],'12-02');
  LoadSound(ZvukRaw[99],'12-03');
  LoadSound(ZvukRaw[100],'12-04');
  LoadSound(ZvukRaw[101],'12-05');
  LoadSound(ZvukRaw[102],'12-06');
  LoadSound(ZvukRaw[103],'12-07');
  LoadSound(ZvukRaw[104],'12-08');

  LoadSound(ZvukRaw[105],'13-01');
  LoadSound(ZvukRaw[106],'13-02');
  LoadSound(ZvukRaw[107],'13-03');
  LoadSound(ZvukRaw[108],'13-04');
  LoadSound(ZvukRaw[109],'13-05');
  LoadSound(ZvukRaw[110],'13-06');
  LoadSound(ZvukRaw[111],'13-07');
  LoadSound(ZvukRaw[112],'13-08');

  LoadSound(ZvukRaw[113],'14-01');
  LoadSound(ZvukRaw[114],'14-02');
  LoadSound(ZvukRaw[115],'14-03');
  LoadSound(ZvukRaw[116],'14-04');
  LoadSound(ZvukRaw[117],'14-05');
  LoadSound(ZvukRaw[118],'14-06');
  LoadSound(ZvukRaw[119],'14-07');
  LoadSound(ZvukRaw[120],'14-08');
End;