mid2rttl.exe -channel 1 midi.mid kanal01.txt
mid2rttl.exe -channel 2 midi.mid kanal02.txt
mid2rttl.exe -channel 3 midi.mid kanal03.txt
mid2rttl.exe -channel 4 midi.mid kanal04.txt
mid2rttl.exe -channel 5 midi.mid kanal05.txt
mid2rttl.exe -channel 6 midi.mid kanal06.txt
mid2rttl.exe -channel 7 midi.mid kanal07.txt
mid2rttl.exe -channel 8 midi.mid kanal08.txt
mid2rttl.exe -channel 9 midi.mid kanal09.txt
mid2rttl.exe -channel 10 midi.mid kanal10.txt
mid2rttl.exe -channel 11 midi.mid kanal11.txt
mid2rttl.exe -channel 12 midi.mid kanal12.txt
mid2rttl.exe -channel 13 midi.mid kanal13.txt
mid2rttl.exe -channel 14 midi.mid kanal14.txt
mid2rttl.exe -channel 15 midi.mid kanal15.txt
mid2rttl.exe -channel 16 midi.mid kanal16.txt

