Procedure SetBet4;
Begin
  Case BetBT4 of
    0: Begin
         If Credit4>=10 then Begin
                               Sazka4:=10;
                               Inc(BetBT4);
                               StopPlay;
                               PlaySound(7);
                             End
                        else Begin
                               Sazka4:=5;
                               BetBT4:=0;
                               StopPlay;
                               PlaySound(7);
                             End;
       End;
    1: Begin
         If Credit4>=20 then Begin
                               Sazka4:=20;
                               Inc(BetBT4);
                               StopPlay;
                               PlaySound(7);
                             End
                        else Begin
                               Sazka4:=5;
                               BetBT4:=0;
                               StopPlay;
                               PlaySound(7);
                             End;
       End;
    2: Begin
         If Credit4>=30 then Begin
                               Sazka4:=30;
                               Inc(BetBT4);
                               StopPlay;
                               PlaySound(7);
                             End
                        else Begin
                               Sazka4:=5;
                               BetBT4:=0;
                               StopPlay;
                               PlaySound(7);
                             End;
       End;
    3: Begin
         If Credit4>=40 then Begin
                               Sazka4:=40;
                               Inc(BetBT4);
                               StopPlay;
                               PlaySound(7);
                             End
                        else Begin
                               Sazka4:=5;
                               BetBT4:=0;
                               StopPlay;
                               PlaySound(7);
                             End;
       End;
    4: Begin
         If Credit4>=50 then Begin
                               Sazka4:=50;
                               Inc(BetBT4);
                               StopPlay;
                               PlaySound(7);
                             End
                        else Begin
                               Sazka4:=5;
                               BetBT4:=0;
                               StopPlay;
                               PlaySound(7);
                             End;
       End;
    5: Begin
         If Credit4>=100 then Begin
                                Sazka4:=100;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
    6: Begin
         If Credit4>=200 then Begin
                                Sazka4:=200;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
    7: Begin
         If Credit4>=300 then Begin
                                Sazka4:=300;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
    8: Begin
         If Credit4>=400 then Begin
                                Sazka4:=400;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
    9: Begin
         If Credit4>=500 then Begin
                                Sazka4:=500;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
   10: Begin
         If Credit4>=600 then Begin
                                Sazka4:=600;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
   11: Begin
         If Credit4>=700 then Begin
                                Sazka4:=700;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
   12: Begin
         If Credit4>=800 then Begin
                                Sazka4:=800;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
   13: Begin
         If Credit4>=900 then Begin
                                Sazka4:=900;
                                Inc(BetBT4);
                                StopPlay;
                                PlaySound(7);
                              End
                         else Begin
                                Sazka4:=5;
                                BetBT4:=0;
                                StopPlay;
                                PlaySound(7);
                              End;
       End;
   14: Begin
         If Credit4>=1000 then Begin
                                 Sazka4:=1000;
                                 Inc(BetBT4);
                                 StopPlay;
                                 PlaySound(7);
                               End
                          else Begin
                                 Sazka4:=5;
                                 BetBT4:=0;
                                 StopPlay;
                                 PlaySound(7);
                               End;
       End;
   15: Begin
         If Credit4>=2000 then Begin
                                 Sazka4:=2000;
                                 Inc(BetBT4);
                                 StopPlay;
                                 PlaySound(7);
                               End
                          else Begin
                                 Sazka4:=5;
                                 BetBT4:=0;
                                 StopPlay;
                                 PlaySound(7);
                               End;
       End;
   16: Begin
         If Credit4>=3000 then Begin
                                 Sazka4:=3000;
                                 Inc(BetBT4);
                                 StopPlay;
                                 PlaySound(7);
                               End
                          else Begin
                                 Sazka4:=5;
                                 BetBT4:=0;
                                 StopPlay;
                                 PlaySound(7);
                               End;
       End;
   17: Begin
         If Credit4>=4000 then Begin
                                 Sazka4:=4000;
                                 Inc(BetBT4);
                                 StopPlay;
                                 PlaySound(7);
                               End
                          else Begin
                                 Sazka4:=5;
                                 BetBT4:=0;
                                 StopPlay;
                                 PlaySound(7);
                               End;
       End;
   18: Begin
         If Credit4>=5000 then Begin
                                 Sazka4:=5000;
                                 Inc(BetBT4);
                                 StopPlay;
                                 PlaySound(7);
                               End
                          else Begin
                                 Sazka4:=5;
                                 BetBT4:=0;
                                 StopPlay;
                                 PlaySound(7);
                               End;
       End;
   19: Begin
         StopPlay;
         PlaySound(7);
         Sazka4:=5;
         BetBT4:=0;
       End;
  End; {Case End}

End;