Function J1: Byte;
Begin
If ((GetMouseX>=111*2) and (GetMouseX<=135*2) and
    (GetMouseY>=123) and (GetMouseY<=133) and
    (GetButton1=1)) then J1:=1
                    else J1:=0;
End;


Function K1: Byte;
Begin
If ((GetMouseX>=146*2) and (GetMouseX<=170*2) and
    (GetMouseY>=123) and (GetMouseY<=133) and
    (GetButton1=1)) then K1:=1
                    else K1:=0;
End;


Function L1: Byte;
Begin
If ((GetMouseX>=182*2) and (GetMouseX<=205*2) and
    (GetMouseY>=123) and (GetMouseY<=133) and
    (GetButton1=1)) then L1:=1
                    else L1:=0;
End;


Function EnterStiskly1: Byte;
Begin
If ((GetMouseX>=72*2) and (GetMouseX<=248*2) and
    (GetMouseY>=80) and (GetMouseY<=104) and
    (GetButton1=1)) then EnterStiskly1:=1
                    else EnterStiskly1:=0;
End;


Function AutostartStiskly1: Byte;
Begin
If ((GetMouseX>=46*2) and (GetMouseX<=72*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then AutostartStiskly1:=1
                    else AutostartStiskly1:=0;
End;


Function StartStiskly1: Byte;
Begin
If ((GetMouseX>=278*2) and (GetMouseX<=319*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then StartStiskly1:=1
                    else StartStiskly1:=0;
End;


Function WinGambleStiskly1: Byte;
Begin
If ((GetMouseX>=74*2) and (GetMouseX<=106*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then WinGambleStiskly1:=1
                    else WinGambleStiskly1:=0;
End;


Function VsaditStiskly1: Byte;
Begin
If ((GetMouseX>=108*2) and (GetMouseX<=146*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then VsaditStiskly1:=1
                    else VsaditStiskly1:=0;
End;


Function DoMultiwinuStiskly1: Byte;
Begin
If ((GetMouseX>=148*2) and (GetMouseX<=198*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then DoMultiwinuStiskly1:=1
                    else DoMultiwinuStiskly1:=0;
End;


Function CollectStiskly1: Byte;
Begin
If ((GetMouseX>=0*2) and (GetMouseX<=44*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then CollectStiskly1:=1
                    else CollectStiskly1:=0;
End;


Function HlavaStiskly1: Byte;
Begin
If ((GetMouseX>=200*2) and (GetMouseX<=238*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then HlavaStiskly1:=1
                    else HlavaStiskly1:=0;
End;


Function OrelStiskly1: Byte;
Begin
If ((GetMouseX>=240*2) and (GetMouseX<=276*2) and
    (GetMouseY>=185) and (GetMouseY<=199) and
    (GetButton1=1)) then OrelStiskly1:=1
                    else OrelStiskly1:=0;
End;


Function VybratCreditStiskly1: Byte;
Begin
If ((GetMouseX>=220*2) and (GetMouseX<=270*2) and
    (GetMouseY>=44) and (GetMouseY<=59) and
    (GetButton1=1)) then VybratCreditStiskly1:=1
                    else VybratCreditStiskly1:=0;
End;


Function VybratMultiwinStiskly1: Byte;
Begin
If ((GetMouseX>=220*2) and (GetMouseX<=270*2) and
    (GetMouseY>=62) and (GetMouseY<=76) and
    (GetButton1=1)) then VybratMultiwinStiskly1:=1
                    else VybratMultiwinStiskly1:=0;
End;


Function BazarStiskly1: Byte;
Begin
If ((GetMouseX>=272*2) and (GetMouseX<=312*2) and
    (GetMouseY>=150) and (GetMouseY<=170) and
    (GetButton1=1)) then BazarStiskly1:=1
                    else BazarStiskly1:=0;
End;


Function ZapsatStiskly1: Byte;
Begin
If ((GetMouseX>=220*2) and (GetMouseX<=267*2) and
    (GetMouseY>=150) and (GetMouseY<=170) and
    (GetButton1=1)) then ZapsatStiskly1:=1
                    else ZapsatStiskly1:=0;
End;


Function Vlozit50Stiskly1: Byte;
Begin
If ((GetMouseX>=285*2) and (GetMouseX<=315*2) and
    (GetMouseY>=43) and (GetMouseY<=59) and
    (GetButton1=1)) then Vlozit50Stiskly1:=1
                    else Vlozit50Stiskly1:=0;
End;


Function Vlozit500Stiskly1: Byte;
Begin
If ((GetMouseX>=285*2) and (GetMouseX<=315*2) and
    (GetMouseY>=62) and (GetMouseY<=78) and
    (GetButton1=1)) then Vlozit500Stiskly1:=1
                    else Vlozit500Stiskly1:=0;
End;
