;****************************************************************************
;
; Information
; ßßßßßßßßßßß
;
;  Title         : NASM-IDE 1.8 Initialisation file
;  Description   : Configuration information for all NASM and NASM-IDE
;                  settings. This file is maintained by NASM-IDE so
;                  manual editing should not be necessary. For more
;                  information, see the NASM-IDE documentation.
;
;****************************************************************************

[ASSEMBLER]
OUTPUT_FORMAT=3
NASM_WARNING=15
NASM_SUPPORTED_WARNINGS=15
PRIMARY_FILE=
RUN_PARAMS=
NASM_LOCATION=C:\NETWIDE\NASM.EXE
CUSTOM_PARAMS=

[DIRECTORIES]
INCLUDE_DIR=
OUTPUT_DIR=C:\OUTPUTS

[ENVIRONMENT]
SCREEN_MODE=0
EDITOR_OPTIONS=6
DESKTOP_AUTOSAVE=0
STARTUP_LOGO=1

[FILE_HISTORY]
FILE_1=C:\SOURCES\STORE1\ENGINE\640WSPRI.ASM
FILE_2=C:\SOURCES\STORE1\ENGINE\320BLOK.ASM
FILE_3=C:\SOURCES\STORE1\ENGINE\640WBLOK.ASM
FILE_4=C:\SOURCES\STORE1\ENGINE\320WBLOK.ASM
FILE_5=C:\SOURCES\STORE1\ENGINE\640BLOK.ASM

[OUTPUT_FORMATS]
OPF_1=COM executable binary file,COM,bin
OPF_2=SYS device driver,SYS,bin
OPF_3=DOS 16 bit OMF object file,OBJ,obj
OPF_4=Microsoft Win32 (i386) object file,OBJ,win32
OPF_5=COFF (i386) object file,O,coff
OPF_6=Relocatable Dynamic Object File Format v1.1,RDF,oldrdf
OPF_7=Relocatable Dynamic Object File Format v2.0,RDF,rdf
