;PC64\DRIVES.INI - KompatibilitÑtsliste externer C64-Laufwerke
;
;AbschnittsÅberschrift ist die jeweilige Einschaltmeldung ohne Fehlernummer,
;Track und Sektor. Tritt ein neues C64-Laufwerk auf, das noch nicht in dieser
;Datei vorhanden ist, werden die Parameter durch einen KompatibilitÑtstest
;automatisch ermittelt und eingetragen.
;
;ReadRecordLength - RecordlÑnge einer geîffneten Datei bestimmen
;
;  1 = Automatische Bestimmung ist mîglich Åber die Formel:
;      Byte[0x00C7 + (Byte[0x022B + Kanal] & 15)]
;
;  0 = Automatische Bestimmung nicht mîglich, der User mu· die RecordlÑnge
;      in einem Dialogfeld von Hand eingeben
;
;CreateDELFile - Datei vom Typ DEL anlegen
;
;  Gelîschte Dateien werden von Diskettenverwaltungsprogrammen eingesetzt,
;  um Trennstriche zu erzeugen. Wenn man eine Datei mit NAME,D,W anlegt,
;  wird der Typ je nach Kanal durch SEQ oder PRG ersetzt, weil "DEL" und
;  "Typ fehlt" dieselbe Kennung 0 besitzen.
;
;  1 = Der Verzeichniseintrag einer Datei kann mit der folgenden Formel
;      ermittelt werden:
;      Puffer = Byte[0x022B + Kanal] & 15
;      Spur   = Byte[0xFE85]
;      Sektor = Byte[0x0260 + Puffer]
;      Offset = Byte[0x0266 + Puffer]
;      Anschlie·end lÑ·t sich Åber eine Direktzugriffsdatei der Verzeichnis-
;      Sektor einlesen und der Typ von 1 (SEQ) auf 0 (DEL) Ñndern.
;
;  0 = Das Anlegen von Dateien des Typs DEL kann nicht abgefangen werden.
;      Somit hÑngt es vom Laufwerk ab, welchen Typ die Datei bekommt.
;      Normalerweise ist das SEQ.
;
;CompliantImage - Laufwerk verarbeitet Disketten im 1541-Format
;
;  Das 1541-Format besteht aus 35 Spuren zu je 21 bis 17 Sektoren Ö 256 Byte.
;  Um mit Diskettenimages zu arbeiten, mu· das Laufwerk dieses Format lesen
;  und schreiben kînnen. Beim KompatibilitÑtstest wird das 1541-Format an den
;  drei Bytes 12h,01h,41h am Anfang von Spur 18 Sektor 0 erkannt.
;
;  1 = Das Kopieren ganzer Disketten ist mîglich. Sie sind als User selbst
;      dafÅr verantwortlich, da· sich eine Diskette im 1541-Format im Laufwerk
;      befindet
;
;  0 = Der Versuch, ganze Disketten zu kopieren, fÅhrt zum Fehler:
;      98,DRIVE NOT 1541 COMPLIANT,00,00
;
;UseL64FastAccess - Schnellader beim Kopieren ganzer Disketten verwenden
;
;  Im Programm L64 ist der Floppybeschleuniger von Michael Niemeyer
;  eingebaut.
;
;  1 = Disketten werden spurweise und mit Schnellader kopiert. Das Lesen
;      einer Diskettenseite dauert 1:37 Minuten, das Schreiben 2:30 Minuten
;
;  0 = Disketten werden sektorweise Åber Direktzugriffsdateien kopiert. Das
;      Lesen einer Diskettenseite dauert 9:15 Minuten, das Schreiben dauert
;      9:35 Minuten

[CBM DOS V2.6 1541]
ReadRecordLength=1
CreateDELFile=1
CompliantImage=1
UseL64FastAccess=1

[64'ER DOS V1 1541]
ReadRecordLength=1
CreateDELFile=1
CompliantImage=1
UseL64FastAccess=1

[CBM DOS V3.0 1571]
ReadRecordLength=1
CreateDELFile=1
CompliantImage=1
UseL64FastAccess=1

[CBM DOS V3.1 1571]
ReadRecordLength=1
CreateDELFile=1
CompliantImage=1
UseL64FastAccess=1

[COPYRIGHT CBM DOS V10 1581]
ReadRecordLength=0
CreateDELFile=0
CompliantImage=0
UseL64FastAccess=0
