                      м ў                                       
               ммммллп
             ллллллл
          ппппппппп
  ВпппппппппппВ  ВппппппппппВ ВппппппппппВ ВпппппппппппппппппппппппппппппппппВ
 Вп ллллллллл В Вп лллллллл Влп лллллллл Влп лллллллллл  лллллллл  ллллллллл пВ
 В ллллл лллл ВмВ ллл ллллл Вл ллл ллллл Вл ллл ллллллл ллл ллллл ллл ллллллл В
 В лллллммммммммм ллл ппппп пп ллл ллллл Вл ллл ллллллл ллл ллллл ллл ллллллл В
 В ммммм лллллллл ллл лллллллл лллппппп  пп ллл ллллллл лллпппппatx%lzллллллл В
 В ллллл лллллллл ллл лллллллл ллл лллллллл ллл ллллллл ллл ллллллллл ллллллл В
 В ллллл лллллллл ллл лллллллл ллл лллллллл ллл ллллллл ллл ллллллллл ллллллл В
 Вм ппппппппппппп пппппппппппп пппппппппппп ппп ппппппп ппппппппппппп пппппп мВ
  пппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппппп
    лллллллллллн                        SCEneT
     ллллллллллл              "the hungarian sceneboard"
      плллллллллл                   +36-1-2285921
        ппллллллллмм                 v.everything
            пппплллллм                  0-24h
                   пппппп п    п          п                melan@hungary.net

                                 World HQ of:
                        AstroideA љ SCEneST Organizing
             Abaddon љ Axioma љ CaPaNЅa љ Dinasty љ Enlightenment
             Exhumers љ Hooligans Crew љ Mandula љ Mortal Compact
           Murmidones љ Promise љ Shock! љ Unique PC љ United Force

                               Hungarian HQ of:
                  COMA љ Dream Recordings љ Hyperopia љ Jamm
               Maak љ OCG љ Orange љ Poison љ Pulse љ Realtech

                                Distro Site of:
                  ByTeam љ Controlled Dreams љ Dubius љ IES
              Emperor љ Hydrogen љ Label Zero љ Nooon љ Urinate

